---
title: "Lab2"
author: "Eleanore Brugh"
date: "2026-03-01"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(sf)
library(tmap)
```
#lab examples
```{r}
 counties <- sf::read_sf("C:/R/Data/CBW/County_Boundaries.shp") %>%
  sf::st_make_valid()
```

```{r}
dams <- sf::read_sf("C:/R/Data/CBW/Dam_or_Other_Blockage_Removed_2012_2017.shp") %>%
  sf::st_make_valid()
```

```{r}
streams <- sf::read_sf("C:/R/Data/CBW/Streams_Opened_by_Dam_Removal_2012_2017.shp") %>%
  sf::st_make_valid() 
```

```{r}
#management practices to reduce nutrient and sediment pollution 
bmps <- read_csv("C:/R/Data/CBW/BMPreport2016_landbmps.csv")
```

```{r}
#names/scores
t.names <- tibble(key = c(1, 2, 3), 
             name = c("Huey", "Dewey", "Louis"))
```
```{r}
t.scores <- tibble(name = c("Louis", "Huey", "Dewey"),
                   grade = c(99, 45, 33))
```

```{r}
#join
#left join starts with the left and then matches it in a table on the right
#can only be used if the tables use the same category name

t.joined <- left_join(t.names, t.scores, by = "name")
t.joined
```

```{r}
t.wonkyNames <- tibble(nombre = c("Dewey", "Louis", "Huey"),
                       x = rep(999),
                       favoriteFood = c("banana", "apple", "carrot"))
```

```{r}
t.joined2 <- left_join(t.names, t.wonkyNames, by = c("name" = "nombre"))
t.joined2
```

```{r}
#tabular data
glimpse(bmps)
```

```{r}
#munging
bmps <- bmps %>% mutate(., FIPS.trimmed = stringr::str_sub(GeographyName, 1, 5))
```

```{r}
bmps %>% group_by(BMPType) %>% summarise(totalCost = sum(Cost)) %>%
  ggplot(., aes(x = BMPType, y = totalCost)) +
  geom_bar(stat = "identity") +
  theme_minimal()

#didn't work, takes data out

summary(bmps$Cost)

```

```{r}
#na.rm = T

bmps %>% group_by(BMPType) %>% summarise(totalCost = sum(Cost, na.rm = T)) %>%
  ggplot(., aes(x = BMPType, y = totalCost)) +
  geom_bar(stat = "identity") +
  theme_minimal()
```

```{r}
#grouping by two factors at the same time
#state and sector grouped with sum total cost

twofactors <- bmps %>% group_by(StateAbbreviation, Sector) %>% 
  summarise(totalCost = sum(Cost))

twofactors

```

```{r}
#review-simple boxplot

bmps %>% ggplot(., aes(x = StateAbbreviation, y = AmountCredited)) +
  geom_boxplot(aes(fill = StateAbbreviation))

```

```{r}
#dramatic subset of data to show skewness
bmps %>% 
  dplyr::filter(., AmountCredited > 1 & AmountCredited < 100) %>% 
  ggplot(., aes(x = StateAbbreviation, y = AmountCredited)) +
  geom_boxplot(aes(fill = StateAbbreviation))
```

```{r}
#facet family of commands 
#can plot multiple dimensions on one plot

bmps %>% 
  dplyr::filter(., AmountCredited > 1 & AmountCredited < 100) %>% 
  ggplot(., aes(x = StateAbbreviation, y = AmountCredited)) +
  geom_boxplot(aes(fill = StateAbbreviation)) +
  facet_grid(Sector~.)

```

```{r}
#log-transform the y-axis as an alternative to removing outliers
#log of 0 is undefined so it removes a lot of data

bmps %>% ggplot(., aes(x = StateAbbreviation, y = AmountCredited)) +
  geom_boxplot(aes(fill = StateAbbreviation)) +
  scale_y_log10() +
  labs(y = "log10(AmountCredited)")

```

```{r}
# demonstration vector
x <- c(1, 2, 3, 4, 5)

# %in% is used to quickly figure out which elements are inside another

7 %in% x # should evaluate False
2 %in% x # should evaluate True

# can also do it with vectors
c(4, 99, 1) %in% x
```




#MY TASKS
```{r}
#Data download

counties <- sf::read_sf("C:/R/Data/CBW/County_Boundaries.shp") %>%
  sf::st_make_valid()

dams <- sf::read_sf("C:/R/Data/CBW/Dam_or_Other_Blockage_Removed_2012_2017.shp") %>%
  sf::st_make_valid()

streams <- sf::read_sf("C:/R/Data/CBW/Streams_Opened_by_Dam_Removal_2012_2017.shp") %>%
  sf::st_make_valid() 

bmps <- read_csv("C:/R/Data/CBW/BMPreport2016_landbmps.csv")

```


#Task 1 ASPATIAL OPS
###1-1
```{r}
#summary statistics

bmps %>%
  group_by(StateAbbreviation) %>%
  summarise(
    minCost = min(Cost, na.rm = TRUE),
    maxCost = max(Cost, na.rm = TRUE),
    meanCost = mean(Cost, na.rm = TRUE),
    medianCost = median(Cost, na.rm = TRUE),
    sdCost = sd(Cost, na.rm = TRUE)
    
  )

```

###1-2
```{r}
#originally did not do the log10, added both x and y log10

bmps %>%
  filter(Unit == "Acres") %>%
  ggplot(aes(x = Cost, y = TotalAmountCredited)) +
  geom_point(alpha = 0.5) +
  scale_x_log10() +
  scale_y_log10() +
  labs(
    title = "Cost vs TotalAmountCredited (BMPS)",
    x = "Cost",
    y = "Total Amount Credited"
  )


```

###1-3
```{r}
#task 1-3
install.packages("stringr")
```
```{r}
library(stringr)

#str_detect paired with filter gets the rows that have the word "cover" and keeps the TRUE rows

bmps %>%
  filter(str_detect(BMP, "Cover")) %>%
  ggplot((aes(x = StateAbbreviation, y = TotalAmountCredited))) +
  geom_boxplot(aes(fill = StateAbbreviation)) +
  labs(
    title = "TotalAmountCredited for Cover Crops (BMP)",
    x = "State",
    y = "TotalAmountCredited"
  )
```

###1-4
```{r}
#year on x-axis

dams %>%
  filter(YEAR != 0) %>%
  ggplot(aes(x = YEAR, y = STATE)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Dam Removals",
    x = "Year",
    y = "State"
  )

```

###1-5
```{r}
#creativity is good for the soul
#backup plan

#bmp cost
sum_cost <- bmps %>%
  group_by(StateAbbreviation) %>%
  summarise(totalCost = sum(Cost, na.rm = TRUE))

#dam count
num_dams <- dams %>%
  group_by(STATE) %>%
  st_drop_geometry() %>%
  summarise(num_dams = n())

the_join <- left_join(sum_cost, num_dams, by = c("StateAbbreviation" = "STATE"))

#Bob Ross Plot that was not my original Bob Ross Plot plan
ggplot(the_join, aes(x = totalCost, y = num_dams)) +
  geom_point(size = 3, color = "chartreuse") +
  labs(
    title = "BMP Cost and Dam Removal",
    x = "Total BMP Cost",
    y = "Number of Dam Removals"
  )
#chartreuse doesn't seem accurate with ggplot

```



#Task 2 SPATIAL OPS
###2-1
```{r}
#Five longest streams

streams %>%
  mutate(length = st_length(geometry)) %>%
  arrange(desc(length)) %>%
  slice_max(length, n=5)

```

###2-2
```{r}
#intersection with new table
streams_county <- st_intersection(streams, counties)
  
top3_counties <- streams_county %>%
  mutate(str_len = as.numeric(st_length(geometry))) %>%
  st_drop_geometry() %>% #did not add this in, until try number 5
  group_by(NAME10) %>%
  summarise(total_len = sum(str_len, na.rm = TRUE), .groups = "drop") %>%
  arrange (desc(total_len)) %>%
  slice(1:3)

```

###2-3
```{r}
#table join
county_bmp <- counties %>%
  st_drop_geometry() %>%
  select(GEOID10, NAME10)

bmps_pt2 <- bmps %>%
  mutate(FIPS = str_sub(GeographyName, 1, 5)) %>%
  left_join(county_bmp, by = c("FIPS" = "GEOID10"))

#summary
sum_bmp_cost <- bmps_pt2 %>%
  group_by(FIPS, NAME10) %>%
  summarise(totalCost = sum(Cost, na.rm = TRUE), .groups = "drop")

#another join
joined_counties <- counties %>%
  left_join(sum_bmp_cost, by = c("GEOID10" = "FIPS"))

#map
library(tmap)

tm_shape(joined_counties) +
  tm_polygons("totalCost",
              palette = "purples",
              title = "Total BMP Costs")
```

###2-4
```{r}
#parentheses compare data points
nearest_stream <- st_nearest_feature(dams, streams)

#indexing aka pulling the correct data
closest_stream <- streams[nearest_stream, ]

```

###2-5
```{r}
#dams removed

dams %>%
  st_drop_geometry() %>%
  group_by(STATE) %>%
  summarise(totalDams = n())

```






